"""add vacancy notification

Revision ID: cc46b6f46e9e
Revises: e7558d9c070d
Create Date: 2022-01-03 22:23:01.050045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc46b6f46e9e'
down_revision = 'e7558d9c070d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'notification')
    # ### end Alembic commands ###
